# Generated by Django 3.2.6 on 2021-08-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='port_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve', models.TextField()),
                ('ip', models.TextField()),
                ('port', models.TextField()),
                ('name', models.TextField()),
                ('score', models.IntegerField()),
                ('description', models.TextField()),
                ('solution', models.TextField()),
                ('scan_id', models.SlugField()),
                ('user', models.IntegerField()),
            ],
        ),
    ]
