# Generated by Django 3.2.6 on 2021-09-01 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_port_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
