# Generated by Django 3.2.6 on 2021-09-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_scan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='id',
            new_name='scan_id',
        ),
    ]
