# Generated by Django 3.2.6 on 2021-09-01 14:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210901_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='id',
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
