# Generated by Django 3.2.6 on 2021-09-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210901_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='scan_id',
        ),
        migrations.AddField(
            model_name='scan',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
