# Generated by Django 3.2.6 on 2021-09-01 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_scan_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='id',
        ),
        migrations.AlterField(
            model_name='scan',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
